import "./globals.css";
import Footer from "./components/Footer";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import { ThemeProvider } from "./context";

require("dotenv").config();

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        {/* I want to spread out the nav main and footer content */}
        <body
          className={`flex flex-col justify-between min-h-screen ${inter.className}`}
        >
          <NavBar />
          <main className="flex flex-col items-center w-full flex-grow">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
